language: python
python:
  - "3.6"
env:
  - SECRET_KEY ='TEST'
services:
  - postgresql
install:
  - pipenv install
script:
  - cd src
  - coverage run --source="account" manage.py test && coverage report

after_success:
  - codecov 
